steps:
  - name: sonarsource/sonar-scanner-cli:latest
    # entrypoint: sonar-scanner
    # args: [ '-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=gcpsourcecodereposcanbc','-Dsonar.projectKey=gcpsourcecodereposcanbc_python-test','-Dsonar.login=${_SONAR_TOKEN}']
    # id: SAST Scan using SonarCloud in GCP DevSecOps Pipeline
    entrypoint: bash
    args: 
        - '-c'
        - |-
          yum update -y
          yum install libpq-dev gcc -y
          pip3 install coverage flask psycopg2
          coverage run code/test_app.py && coverage xml
          ls -l
          sonar-scanner -Dsonar.login=${_SONAR_TOKEN}
    id: SAST Scan using SonarCloud in GCP DevSecOps Pipeline